"""Add advance_closed to Customer

Revision ID: 6d8999b90851
Revises: b63fbcbeeada
Create Date: 2025-07-09 11:44:34.937579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8999b90851'
down_revision = 'b63fbcbeeada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance_closed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('advance_closed')

    # ### end Alembic commands ###
