"""Make allowed_days and order_date user-defined

Revision ID: a68e8f1c86f3
Revises: d24bbf65348d
Create Date: 2025-06-12 08:12:14.497349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68e8f1c86f3'
down_revision = 'd24bbf65348d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
