"""Add advance to Customer

Revision ID: b63fbcbeeada
Revises: c0af27278a0a
Create Date: 2025-07-07 23:07:05.259724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63fbcbeeada'
down_revision = 'c0af27278a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance', sa.Float(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('advance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('advance')

    # ### end Alembic commands ###
