"""Add advance to Order

Revision ID: c0af27278a0a
Revises: c4f6ed906aa6
Create Date: 2025-07-07 22:41:24.143230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0af27278a0a'
down_revision = 'c4f6ed906aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('advance')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('advance')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
