"""Add advance to Customer

Revision ID: c4f6ed906aa6
Revises: 9f81d66065e2
Create Date: 2025-07-07 17:45:32.764557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f6ed906aa6'
down_revision = '9f81d66065e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance', sa.Float(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('advance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('advance')

    # ### end Alembic commands ###
