"""Add return fields to Order model

Revision ID: d24bbf65348d
Revises: 3534af8e19f1
Create Date: 2025-06-12 07:44:00.182863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24bbf65348d'
down_revision = '3534af8e19f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_days', sa.Integer(), nullable=True))
        batch_op.drop_column('expected_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_days', sa.INTEGER(), nullable=True))
        batch_op.drop_column('used_days')
        batch_op.drop_column('allowed_days')

    # ### end Alembic commands ###
